---  
application_rule_collections:
  app_rule_collection1:
    name: "app_rule_collection1"
    priority: "500"
    actiontype: "Deny"
    rules:
    - name: "app_rule_collection1_rule1"
      protocols:
      - protocolType: "Http"
        port: "80"
      - protocolType: "Https"
        port: "443"
      sourceAddresses: ["10.0.0.1"]
      targetFqdns: ["*.microsoft.com"]
      fqdnTags: []
      sourceIpGroups: []

network_rule_collections:
  Basic-RuleCollection:
    priority: "1000"
    action: "Allow"
    rules:
      Ping:
        protocols             : ["ICMP"]
        source_addresses      : ["50.4.4.4", "50.5.4.4"]
        source_ip_groups      : []
        destination_addresses  : ["8.8.8.8", "8.8.4.4"]
        destination_ip_groups : []
        destination_fqdns     : []
        destination_ports     : ["*"]
      # RDP:
      #   protocols             : ["TCP"]
      #   source_ip_groups      : [azurerm_ip_group.MainUSVnetIPSpace.id]
      #   destination_ip_groups : []
      #   destination_fqdns     : ["test.home.com"]
      #   destination_ports     : ["3389"]
